// main.js
document.addEventListener("DOMContentLoaded", () => {
  const createForm = document.getElementById("createForm");
  const joinForm = document.getElementById("joinForm");
  const submitForm = document.getElementById("submitForm");
  const output = document.getElementById("output");

  async function postJSON(url, data) {
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });

      const text = await res.text();
      let result;
      try {
        result = JSON.parse(text);
      } catch {
        result = text;
      }
      return { ok: res.ok, result };
    } catch (err) {
      console.error("Network error:", err);
      return { ok: false, result: { error: "Failed to connect to server." } };
    }
  }

  // --- CREATE LOBBY (host ID auto-generated by backend) ---
  if (createForm) {
    createForm.addEventListener("submit", async (e) => {
      e.preventDefault();

      const data = {
        hostName: document.getElementById("hostName").value.trim(),
      };

      const { ok, result } = await postJSON("/api/game/create", data);

      if (ok) {
        // Store backend-generated ID
        localStorage.setItem("playerId", result.playerId);
        localStorage.setItem("playerName", data.hostName);
        localStorage.setItem("lobbyCode", result.lobbyCode);
        localStorage.setItem("isHost", "true");

        window.location.href =
          `lobby.html?code=${result.lobbyCode}&playerId=${result.playerId}&name=${data.hostName}&isHost=true`;
      } else {
        output.textContent = result.error || "Failed to create lobby.";
      }
    });
  }

  // --- JOIN LOBBY (player ID auto-generated by backend) ---
  if (joinForm) {
    joinForm.addEventListener("submit", async (e) => {
      e.preventDefault();

      const data = {
        code: document.getElementById("lobbyCode").value.trim(),
        name: document.getElementById("name").value.trim(),
      };

      const { ok, result } = await postJSON("/api/game/join", data);

      if (ok) {
        localStorage.setItem("playerId", result.playerId);
        localStorage.setItem("playerName", data.name);
        localStorage.setItem("lobbyCode", data.code);
        localStorage.setItem("isHost", "false");

        window.location.href = "lobby.html";
      } else {
        output.textContent = result.error || "Failed to join lobby.";
      }
    });
  }

  // --- SUBMIT ANSWERS (unchanged) ---
  if (submitForm) {
    submitForm.addEventListener("submit", async (e) => {
      e.preventDefault();

      const data = {
        playerId: document.getElementById("playerId").value.trim(),
        roundIndex: parseInt(document.getElementById("roundIndex").value),
        answers: document
          .getElementById("answers")
          .value.split(",")
          .map((a) => a.trim()),
      };

      const { ok, result } = await postJSON("/api/game/submit", data);
      output.textContent = ok
        ? JSON.stringify(result, null, 2)
        : result.error || "Error submitting answers.";
    });
  }
});
